[profile.default]
src = "src"
test = "test"
out = "forge-out"
libs = []
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
solc_version = "0.8.33"
ffi = false
fs_permissions = [{ access = "read", path = "./out" }]

[profile.ci]
src = "src"
test = "test"
out = "forge-out"
libs = []
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
solc_version = "0.8.33"
ffi = false
fs_permissions = [{ access = "read", path = "./out" }]
